export const DataCategory2 = [
  {
    id: '',
    text: 'Перечень точек роста',
    price: 'Млрд. руб.',
    head: true,
  },
  {
    text: 'Аэропорты',
    rowTitle: true,
  },
  {
    id: 1,
    text: 'Шереметьево',
    price: '56,4',
    width: '30px',
    height: '30px',
    top: '29.5%',
    left: '42.6%',
  },
  {
    id: 2,
    text: 'Домодедово',
    price: '82,4',
    width: '30px',
    height: '30px',
    top: '46.8%',
    left: '52.7%',
  },
  {
    id: 3,
    text: 'Жуковский',
    price: '32,2',
    width: '30px',
    height: '30px',
    top: '41.8%',
    left: '58.8%',
  },
  {
    id: 4,
    text: 'Кубинка',
    price: '23,3',
    width: '30px',
    height: '30px',
    top: '42%',
    left: '29.3%',
  },
  {
    text: 'Точки роста',
    rowTitle: true,
  },
  {
    id: 5,
    text: 'Есипово',
    price: '4,24',
    width: '30px',
    height: '30px',
    top: '23%',
    left: '36.9%',
  },
  {
    id: 6,
    text: 'Белый Раст',
    price: '63,5',
    width: '30px',
    height: '30px',
    top: '26.6%',
    left: '45.9%',
  },
  {
    id: 7,
    text: 'Терминал ТЛЦ Восточный',
    price: '29,3',
    width: '30px',
    height: '30px',
    top: '37.8%',
    left: '60.4%',
  },
  {
    id: 8,
    text: 'Борилово',
    price: '0,6',
    width: '30px',
    height: '30px',
    top: '33.8%',
    left: '61.2%',
  },
  {
    id: 9,
    text: 'Северное Домодедово ',
    price: '36,4',
    width: '26px',
    height: '26px',
    top: '44.8%',
    left: '50.2%',
  },
  {
    id: 10,
    text: 'Белые столбы',
    price: '3,49',
    width: '24px',
    height: '24px',
    top: '49.2%',
    left: '50.9%',
  },
  {
    id: 11,
    text: 'Патриот',
    price: null,
    width: '30px',
    height: '30px',
    top: '45%',
    left: '32.5%',
  },
  {
    id: 12,
    text: 'Инновационный «Центр Жуковский»',
    price: null,
    width: '30px',
    height: '30px',
    top: '42.6%',
    left: '55%',
  },
  {
    id: 13,
    text: 'Инновационный Центр «Сколково»',
    price: null,
    width: '30px',
    height: '30px',
    top: '42%',
    left: '43%',
  },
  {
    text: 'Особые экономические зоны',
    rowTitle: true,
  },
  {
    id: 14,
    text: 'Дубна',
    price: null,
    width: '30px',
    height: '30px',
    top: '4.4%',
    left: '40.4%',
  },
  {
    id: 15,
    text: 'Фрязино «Исток»',
    price: '50,3',
    width: '30px',
    height: '30px',
    top: '29.3%',
    left: '54.2%',
  },
  {
    id: 16,
    text: 'Ступино «Квадрат»',
    price: '38,7',
    width: '30px',
    height: '30px',
    top: '58%',
    left: '55%',
  },
  {
    id: 17,
    text: 'Кашира (планируемый)',
    price: null,
    width: '30px',
    height: '30px',
    top: '64%',
    left: '55%',
  },
  {
    id: 18,
    text: 'Максимиха (планируемый)',
    price: '0,96',
    width: '30px',
    height: '30px',
    top: '52.7%',
    left: '51%',
  },
  {
    id: 19,
    text: 'Культурный центр Сергиев Посад ',
    price: null,
    width: '30px',
    height: '30px',
    top: '17%',
    left: '55.8%',
  },
  {
    text: 'Итого',
    price: '425,24',
    itog: true,
  },
];
