export const DataCategory2 = [
  {
    id: '',
    text: 'Перечень точек роста',
    price: 'Млрд. руб.',
    head: true,
  },
  {
    text: 'Аэропорты',
    rowTitle: true,
  },
  {
    id: 1,
    text: '<span class="link">Шереметьево</span>',
    price: '56,4',
    top: '26.6%',
    left: '41.8%',
  },
  {
    id: 2,
    text: '<span class="link">Домодедово</span>',
    price: '83,33',
    top: '44%',
    left: '53.3%',
  },
  {
    id: 3,
    text: '<span class="link">Жуковский</span>',
    price: '32,02',
    top: '39.5%',
    left: '58%',
  },
  {
    id: 4,
    text: '<span class="link">Кубинка</span>',
    price: '23,3',
    top: '39%',
    left: '30.3%',
  },
  {
    text: 'Точки роста',
    rowTitle: true,
  },
  {
    id: 5,
    text: '<span class="link">Есипово</span>',
    price: '4,24',
    top: '20%',
    left: '37.5%',
  },
  {
    id: 6,
    text: '<span class="link">Белый Раст</span>',
    price: '63,5',
    top: '23.4%',
    left: '45.9%',
  },
  {
    id: 7,
    text: '<span class="link">Терминал ТЛЦ Восточный</span>',
    price: '29,3',
    top: '34.4%',
    left: '59.4%',
  },
  {
    id: 8,
    text: '<span class="link">Борилово</span>',
    price: '0,6',
    top: '30.4%',
    left: '62.2%',
  },
  {
    id: 9,
    text: '<span class="link">Северное Домодедово</span>',
    price: '36,4',
    top: '42.8%',
    left: '48.2%',
  },
  {
    id: 10,
    text: '<span class="link">Белые столбы</span>',
    price: '3,5',
    top: '47.3%',
    left: '50%',
  },
  {
    id: 11,
    text: '<span class="link">Патриот</span>',
    price: '23,3',
    top: '39.5%',
    left: '31.3%',
  },
  {
    id: 12,
    text: '<span class="link">Инновационный «Центр Жуковский»</span>',
    price: '10,12',
    top: '39.6%',
    left: '56%',
  },
  {
    id: 13,
    text: '<span class="link">Инновационный Центр «Сколково»</span>',
    price: '3,89',
    top: '39%',
    left: '41.6%',
  },
  {
    text: 'Особые экономические зоны',
    rowTitle: true,
  },
  {
    id: 14,
    text: '<span class="link">Дубна</span>',
    price: '3,5',
    top: '2.4%',
    left: '41%',
  },
  {
    id: 15,
    text: '<span class="link">Фрязино «Исток»</span>',
    price: '50,3',
    top: '26.4%',
    left: '54.4%',
  },
  {
    id: 16,
    text: 'Ступино «Квадрат»',
    price: '38,7',
    top: '54.6%',
    left: '55.4%',
  },
  {
    id: 17,
    text: '<span class="link">Кашира (планируемый)</span>',
    price: '17,9',
    top: '61%',
    left: '55%',
  },
  {
    id: 18,
    text: '<span class="link">Максимиха (планируемый)</span>',
    price: '3,89',
    top: '49.3%',
    left: '50.7%',
  },
  {
    id: 19,
    text: '<span class="link">Культурный центр Сергиев Посад</span>',
    price: '—',
    top: '14%',
    left: '54.8%',
  },
  {
    text: 'Итого',
    price: '484,19',
    itog: true,
  },
];
