// страница №8 в презентации (приложение)

export const DataCategory5 = [
  {
    id: '№',
    area: 'Район',
    buildingArea: 'Планируемая площадь застройки (млн. кв. м.)',
    populationSize: 'Планируемая численность населения (тыс. чел.)',
    jobSize: 'Планируемое кол-во рабочих мест (тыс.)',
    head: true,
  },
  {
    id: '1',
    area: '<span class="link">Ленинский район</span>',
    buildingArea: '14,7',
    populationSize: '508,3',
    jobSize: '243,3',
  },
  {
    id: '2',
    area: '<span class="link">Красногорск</span>',
    buildingArea: '9,06',
    populationSize: '259',
    jobSize: '125,7',
  },
  {
    id: '',
    area: 'в т.ч. Путилковское шоссе (ЛРТ Митино) ',
    buildingArea: '1,92',
    populationSize: '62,4',
    jobSize: '20,2',
  },
  {
    id: '',
    area: 'в т.ч. связка с Пятницким шоссе',
    buildingArea: '9,06',
    populationSize: '34,7',
    jobSize: '7,6',
  },
  {
    id: '3',
    area: '<span class="link">Домодедово</span>',
    buildingArea: '6,58',
    populationSize: '209,5',
    jobSize: '181,5 ',
  },
  {
    id: '4',
    area: 'Люберцы',
    buildingArea: '4,95',
    populationSize: '165',
    jobSize: '134,6',
  },
  {
    id: '5',
    area: '<span class="link">Мытищи</span>',
    buildingArea: '4,02',
    populationSize: '142,2',
    jobSize: '88,2',
  },
  {
    id: '6',
    area: '<span class="link">Одинцово</span>',
    buildingArea: '2,13',
    populationSize: '73,4',
    jobSize: '58,8',
  },
  {
    id: '7',
    area: '<span class="link">Застройка ПИК Котельники</span>',
    buildingArea: '1,18',
    populationSize: '40,3',
    jobSize: '33,5',
  },
  {
    area: 'Итого',
    buildingArea: '37,7',
    populationSize: '1 285,4',
    jobSize: '653',
    itog: true,
  },
];
